### ISSUE TITLE
error while running test_lgn.py

### ISSUE THREAD

**Issue by meltingCat** [chanokin/vision#6]
hi, @chanokin .I got the problem with **No module named 'model_binaries'** while running **test_lgn.py**. Not sure why the file exists but I cant import.
```
jovyan@f7c7c0462e94:~/Documents/vision$ python3 test_lgn.py
Traceback (most recent call last):
  File "test_lgn.py", line 1, in <module>
    from vision_common import *
  File "/home/jovyan/Documents/vision/vision_common.py", line 5, in <module>
    from vision.spike_tools.vis import my_imshow, plot_spikes, \
  File "/home/jovyan/Documents/vision/vision/__init__.py", line 1, in <module>
    from vision.convolution.python_models.convolution_population import \
  File "/home/jovyan/Documents/vision/vision/convolution/__init__.py", line 1, in <module>
    from model_binaries import __file__ as binaries_path
ModuleNotFoundError: No module named 'model_binaries'
```
I have set up **vision** with the command below
```
cd vision
python3 setup.py build
python3 setup.py install --user
```

**Comment by chanokin** [comment]
Oh dear :disappointed: I'm sorry, I was working on a custom module but forgot to remove it from the release. You can safely delete the .../vision/vision/convolution folder.

**Comment by meltingCat** [comment]
Hi, @chanokin .There's some problem that needs your help.
I thought that the `ModuleNotFoundError` bugs were because of using python3. It can be fix. But the codes were using spynnaker7 which was [no longer supported.](https://github.com/SpiNNakerManchester/sPyNNaker7)
```
jovyan@f7c7c0462e94:~/Documents/vision$ python3 test_lgn.py
Traceback (most recent call last):
  File "test_lgn.py", line 1, in <module>
    from vision_common import *
  File "/home/jovyan/Documents/vision/vision_common.py", line 20, in <module>
    from vision.retina import Retina, dvs_modes, MERGED
  File "/home/jovyan/Documents/vision/vision/retina.py", line 10, in <module>
    from spynnaker7.pyNN.external_devices import \
ModuleNotFoundError: No module named 'spynnaker7'
```

**Comment by meltingCat** [comment]
@chanokin I'm using **Branch: master** with python 3.5.5.

**Comment by chanokin** [comment]
Yikes! I will have to do a deep dive into this but it will take some time. Depending on SpyNNaker 7 is may be the worst part but should be fixable.

**Comment by meltingCat** [comment]
Hi, @chanokin I fixed the problem by replacing 
`from spynnaker.pyNN.external_devices import SpynnakerExternalDevicePluginManager as ex`
to
`import spynnaker.pyNN.spynnaker_external_device_plugin_manager as ex`
but I got the error below
```
jovyan@f7c7c0462e94:~/Documents/vision$ python3 test_lgn.py
reading spikes from:
../pyDVS/mnist_spikes/mnist_behave_SACCADE_pol_MERGED_enc_TIME_thresh_12_hist_99_inh_False___10_frames_at_100fps_32x32_res_spikes/t10k/
Delete previous run --------------------------------------------
Getting spikes -------------------------------------------------
../pyDVS/mnist_spikes/mnist_behave_SACCADE_pol_MERGED_enc_TIME_thresh_12_hist_99_inh_False___10_frames_at_100fps_32x32_res_spikes/t10k/
Traceback (most recent call last):
  File "test_lgn.py", line 235, in <module>
    start_time, delete_before=delete_before)
  File "/home/jovyan/Documents/vision/vision/spike_tools/pattern/pattern_generator.py", line 442, in img_spikes_from_to
    raise Exception("Unable to locate files in dir:\n\t\t%s"%path)
Exception: Unable to locate files in dir:
                ../pyDVS/mnist_spikes/mnist_behave_SACCADE_pol_MERGED_enc_TIME_thresh_12_hist_99_inh_False___10_frames_at_100fps_32x32_res_spikes/t10k/
```
I have been converting images mnist_to_spikes.py
```
jovyan@f7c7c0462e94:~/Documents/pyDVS$ python3 by mnist_to_spikes.py
cam_fps, frame_time_ms, num_bins, t_bin_ms
100 10.0 10.0 1.0
num_bins, t_bin_ms
10.0 1.0
using log spike time coding? False
./mnist_spikes/mnist_behave_SACCADE_pol_MERGED_enc_TIME_thresh_12_hist_99_inh_False___10_frames_at_100fps_32x32_res_spikes
done converting images!!!
```
```
jovyan@f7c7c0462e94:~/Documents/pyDVS$ cd mnist_spikes/mnist_behave_SACCADE_pol_MERGED_enc_TIME_thresh_12_hist_99_inh_False___10_frames_at_100fps_32x32_res_spikes/t10k/
jovyan@f7c7c0462e94:~/Documents/pyDVS/mnist_spikes/mnist_behave_SACCADE_pol_MERGED_enc_TIME_thresh_12_hist_99_inh_False___10_frames_at_100fps_32x32_res_spikes/t10k$ ls
mnist__img_00000.txt  mnist__img_00004.txt  mnist__img_00008.txt
mnist__img_00001.txt  mnist__img_00005.txt  mnist__img_00009.txt
mnist__img_00002.txt  mnist__img_00006.txt
mnist__img_00003.txt  mnist__img_00007.txt
```

**Comment by chanokin** [comment]
I think that with the notebook I was compressing the spike files at the end. Can you try using bz2 compression on one of the txt files? The function looks for a txt.bz2 extension and then decompresses the file to read the spikes off.

**Comment by meltingCat** [comment]
Hi, @chanokin. Not sure if I ran with spynnaker8?
```
jovyan@f7c7c0462e94:~/Documents/vision$ python3 test_lgn.py
reading spikes from:
/home/jovyan/Documents/pyDVS/mnist_spikes/mnist_behave_SACCADE_pol_MERGED_enc_TIME_thresh_12_hist_99_inh_False___10_frames_at_100fps_32x32_res_spikes/t10k/
Delete previous run --------------------------------------------
Getting spikes -------------------------------------------------
100.16% base t 000000   neuron 001144   time 000100     max t 001000

Plotting Camera ------------------------------------------------
Simulating network ---------------------------------------------
Traceback (most recent call last):
  File "test_lgn.py", line 274, in <module>
    direction_on=direction_on)
  File "test_lgn.py", line 10, in run_sim
    sim.setup(timestep=1., max_delay=140., min_delay=1.)
AttributeError: module 'spynnaker.pyNN' has no attribute 'setup'
```

**Comment by chanokin** [comment]
If you run it with `spynnaker8` you would need to change the import to `import spynnaker8 as sim` but my code was developed with spynnaker7. I bet just changing to spynnaker8 will introduce more problems than solutions.

I think we may run into another problem, I believe I did custom connectors which may not be present any more.

**Comment by chanokin** [comment]
You could also install [sPyNNaker7](https://github.com/SpiNNakerManchester/sPyNNaker7) and change that import to `import spynnaker7 as sim`

**Comment by pabogdan** [comment]
@chanokin sPyNNaker7 no longer exists.

**Comment by chanokin** [comment]
@pabogdan whaaat? then most (if not all) of this is pretty pointless. I need to redo the whole thing for PyNN 8/9 :sob:

**Comment by pabogdan** [comment]
Sorry!

**Comment by meltingCat** [comment]
@chanokin I replaced `import spynnaker7.pyNN as sim` with `import pyNN.spiNNaker as sim`.
But just like you said introduce more problems during [sPyNNaker8](https://github.com/SpiNNakerManchester/sPyNNaker8)

```
jovyan@f7c7c0462e94:~/Documents/vision$ python3 test_lgn.py
reading spikes from:
/home/jovyan/Documents/pyDVS/mnist_spikes/mnist_behave_SACCADE_pol_MERGED_enc_TIME_thresh_12_hist_99_inh_False___10_frames_at_100fps_32x32_res_spikes/t10k/
Delete previous run --------------------------------------------
Getting spikes -------------------------------------------------
100.16% base t 000000   neuron 001144   time 000098     max t 001000

Plotting Camera ------------------------------------------------
Simulating network ---------------------------------------------
['/home/jovyan/.local/lib/python3.6/site-packages/spinn_front_end_common/interface/spinnaker.cfg', '/home/jovyan/.local/lib/python3.6/site-packages/spynnaker/pyNN/spynnaker.cfg', '/home/jovyan/.spynnaker.cfg']
2020-03-10 15:04:30 INFO: Read cfg files: /home/jovyan/.local/lib/python3.6/site-packages/spinn_front_end_common/interface/spinnaker.cfg, /home/jovyan/.local/lib/python3.6/site-packages/spynnaker/pyNN/spynnaker.cfg, /home/jovyan/.spynnaker.cfg
2020-03-10 15:04:30 INFO: Will search these locations for binaries: /home/jovyan/.local/lib/python3.6/site-packages/spinn_front_end_common/common_model_binaries : /home/jovyan/.local/lib/python3.6/site-packages/spynnaker/pyNN/model_binaries
2020-03-10 15:04:30 INFO: Setting time scale factor to 1.
2020-03-10 15:04:30 INFO: Setting machine time step to 1000 micro-seconds.
Traceback (most recent call last):
  File "test_lgn.py", line 274, in <module>
    direction_on=direction_on)
  File "test_lgn.py", line 22, in run_sim
    cam.record()
TypeError: record() missing 1 required positional argument: 'variables'
```
